name: coffe_shop_ui_challenge
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9
  provider: ^6.1.1
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  xml: ^6.5.0
  path: ^1.8.3
  flutter_typeahead: ^5.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/gpx/


  fonts:
    - family: Sora
      fonts:
        - asset: assets/fonts/Sora/static/Sora-Light.ttf
          weight: 300
        - asset: assets/fonts/Sora/static/Sora-Regular.ttf
          weight: 400
        - asset: assets/fonts/Sora/static/Sora-Medium.ttf
          weight: 500        
        - asset: assets/fonts/Sora/static/Sora-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Sora/static/Sora-Bold.ttf
          weight: 700
        - asset: assets/fonts/Sora/static/Sora-ExtraBold.ttf
          weight: 900
        
  
